# Generated by Django 5.1.6 on 2025-02-27 16:48

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='visible_username',
            field=models.CharField(help_text='non-unique username which is preferably visible for the other users', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='visible username'),
        ),
    ]
