# Generated by Django 5.1.6 on 2025-02-27 16:56

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_email_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=users.models.User.generate_avatar_path, verbose_name='avatar'),
        ),
    ]
