# Generated by Django 5.1.6 on 2025-03-02 11:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=users.models.User.generate_avatar_path, verbose_name='avatar'),
        ),
    ]
